/* Allegro datafile object indexes, produced by grabber v3.12 */
/* Datafile: d:\cpp\omat\volcano2\data.dat */
/* Date: Thu Feb 22 14:13:11 2001 */
/* Do not hand edit! */

#define DATARMORHEAD1                    0        /* BMP  */
#define DATARMORHEAD2                    1        /* BMP  */
#define DATARMORHEAD3                    2        /* BMP  */
#define DATARMORHEAD4                    3        /* BMP  */
#define DATARMORHEAD5                    4        /* BMP  */
#define DATARMORHEAD6                    5        /* BMP  */
#define DATARMORLEGS1                    6        /* BMP  */
#define DATARMORLEGS2                    7        /* BMP  */
#define DATARMORLEGS3                    8        /* BMP  */
#define DATARMORLEGS4                    9        /* BMP  */
#define DATARMORLEGS5                    10       /* BMP  */
#define DATARMORLEGS6                    11       /* BMP  */
#define DATARMORTORSO1                   12       /* BMP  */
#define DATARMORTORSO2                   13       /* BMP  */
#define DATARMORTORSO3                   14       /* BMP  */
#define DATARMORTORSO4                   15       /* BMP  */
#define DATARMORTORSO5                   16       /* BMP  */
#define DATARMORTORSO6                   17       /* BMP  */
#define DATBAZOOKA                       18       /* BMP  */
#define DATBLD0001                       19       /* BMP  */
#define DATBLD0001_2                     20       /* BMP  */
#define DATBLD0001_3                     21       /* BMP  */
#define DATBLD0002                       22       /* BMP  */
#define DATBLD0002_2                     23       /* BMP  */
#define DATBLD0002_3                     24       /* BMP  */
#define DATBLD0003                       25       /* BMP  */
#define DATBLD0003_2                     26       /* BMP  */
#define DATBLD0003_3                     27       /* BMP  */
#define DATBLD0004                       28       /* BMP  */
#define DATBLD0004_2                     29       /* BMP  */
#define DATBLD0004_3                     30       /* BMP  */
#define DATBLD0004_4                     31       /* BMP  */
#define DATBLD0004_5                     32       /* BMP  */
#define DATBLD0004_6                     33       /* BMP  */
#define DATBLD0004_7                     34       /* BMP  */
#define DATBLD0004_8                     35       /* BMP  */
#define DATBLD0004_9                     36       /* BMP  */
#define DATBLD0004_91                    37       /* BMP  */
#define DATBLD0004_92                    38       /* BMP  */
#define DATBLD0004_93                    39       /* BMP  */
#define DATBLD0004_94                    40       /* BMP  */
#define DATBLD0004_95                    41       /* BMP  */
#define DATBLD0004_96                    42       /* BMP  */
#define DATBLD0004_97                    43       /* BMP  */
#define DATBLD0004_98                    44       /* BMP  */
#define DATBLD0004_99                    45       /* BMP  */
#define DATBLD0004_991                   46       /* BMP  */
#define DATBLD0004_992                   47       /* BMP  */
#define DATBLD0004_993                   48       /* BMP  */
#define DATBLD0004_994                   49       /* BMP  */
#define DATBLD0004_995                   50       /* BMP  */
#define DATBLD0004_996                   51       /* BMP  */
#define DATBLD0005                       52       /* BMP  */
#define DATBLD0005_02                    53       /* BMP  */
#define DATBLD0005_03                    54       /* BMP  */
#define DATBLD0005_04                    55       /* BMP  */
#define DATBLD0005_05                    56       /* BMP  */
#define DATBLD0005_06                    57       /* BMP  */
#define DATBLD0005_07                    58       /* BMP  */
#define DATBLD0005_08                    59       /* BMP  */
#define DATBLD0005_09                    60       /* BMP  */
#define DATBLD0005_10                    61       /* BMP  */
#define DATBLD0005_11                    62       /* BMP  */
#define DATBLD0005_12                    63       /* BMP  */
#define DATBLD0005_13                    64       /* BMP  */
#define DATBLD0005_14                    65       /* BMP  */
#define DATBLD0005_15                    66       /* BMP  */
#define DATBLD0005_16                    67       /* BMP  */
#define DATBLD0005_17                    68       /* BMP  */
#define DATBLD0005_18                    69       /* BMP  */
#define DATBLD0005_19                    70       /* BMP  */
#define DATBLD0005_20                    71       /* BMP  */
#define DATBLD0005_21                    72       /* BMP  */
#define DATBLD0005_22                    73       /* BMP  */
#define DATBLD0005_23                    74       /* BMP  */
#define DATBLD0005_24                    75       /* BMP  */
#define DATBLD0006                       76       /* BMP  */
#define DATBLD0007                       77       /* BMP  */
#define DATBULLETPIC01                   78       /* BMP  */
#define DATBULLETPIC02                   79       /* BMP  */
#define DATBULLETPIC03                   80       /* BMP  */
#define DATBULLETPIC04                   81       /* BMP  */
#define DATBULLETPIC05                   82       /* BMP  */
#define DATBULLETPIC06                   83       /* BMP  */
#define DATBULLETPIC07                   84       /* BMP  */
#define DATBULLETPIC08                   85       /* BMP  */
#define DATBULLETPIC09                   86       /* BMP  */
#define DATBULLETPIC10                   87       /* BMP  */
#define DATCURSOR                        88       /* BMP  */
#define DATDAMAGE001                     89       /* BMP  */
#define DATDAMAGE002                     90       /* BMP  */
#define DATDAMAGE003                     91       /* BMP  */
#define DATDHEAD1                        92       /* BMP  */
#define DATDHEAD2                        93       /* BMP  */
#define DATDHEAD3                        94       /* BMP  */
#define DATDLEGS1                        95       /* BMP  */
#define DATDLEGS2                        96       /* BMP  */
#define DATDLEGS3                        97       /* BMP  */
#define DATDTORSO1                       98       /* BMP  */
#define DATDTORSO2                       99       /* BMP  */
#define DATDTORSO3                       100      /* BMP  */
#define DATGORE01                        101      /* BMP  */
#define DATGORE02                        102      /* BMP  */
#define DATGORE03                        103      /* BMP  */
#define DATGORE04                        104      /* BMP  */
#define DATGORE05                        105      /* BMP  */
#define DATGORE06                        106      /* BMP  */
#define DATGORE07                        107      /* BMP  */
#define DATGORE08                        108      /* BMP  */
#define DATGORE11                        109      /* BMP  */
#define DATGORE12                        110      /* BMP  */
#define DATGORE13                        111      /* BMP  */
#define DATGORE14                        112      /* BMP  */
#define DATGORE15                        113      /* BMP  */
#define DATGORE16                        114      /* BMP  */
#define DATGORE17                        115      /* BMP  */
#define DATGORE18                        116      /* BMP  */
#define DATGOREHAND11                    117      /* BMP  */
#define DATGOREHAND12                    118      /* BMP  */
#define DATGOREHAND21                    119      /* BMP  */
#define DATGOREHAND22                    120      /* BMP  */
#define DATGOREHAND31                    121      /* BMP  */
#define DATGOREHAND32                    122      /* BMP  */
#define DATGOREHAND41                    123      /* BMP  */
#define DATGOREHAND42                    124      /* BMP  */
#define DATGORELEGS1                     125      /* BMP  */
#define DATGORELEGS2                     126      /* BMP  */
#define DATGORELEGS21                    127      /* BMP  */
#define DATGORELEGS22                    128      /* BMP  */
#define DATGRAYPLATE                     129      /* BMP  */
#define DATGUN0001                       130      /* BMP  */
#define DATGUN0002                       131      /* BMP  */
#define DATGUN0003                       132      /* BMP  */
#define DATGUN0004                       133      /* BMP  */
#define DATGUN0005                       134      /* BMP  */
#define DATGUN0006                       135      /* BMP  */
#define DATGUN0007                       136      /* BMP  */
#define DATGUN0008                       137      /* BMP  */
#define DATGUN0009                       138      /* BMP  */
#define DATGUN0010                       139      /* BMP  */
#define DATGUN0011                       140      /* BMP  */
#define DATGUN0012                       141      /* BMP  */
#define DATGUN0013                       142      /* BMP  */
#define DATGUN0014                       143      /* BMP  */
#define DATGUNB01                        144      /* BMP  */
#define DATGUNB02                        145      /* BMP  */
#define DATGUNB03                        146      /* BMP  */
#define DATGUNB04                        147      /* BMP  */
#define DATGUNB05                        148      /* BMP  */
#define DATGUNB06                        149      /* BMP  */
#define DATGUNB07                        150      /* BMP  */
#define DATGUNB08                        151      /* BMP  */
#define DATGUNB09                        152      /* BMP  */
#define DATGUNB10                        153      /* BMP  */
#define DATGUNB11                        154      /* BMP  */
#define DATGUNB12                        155      /* BMP  */
#define DATGUNBL01                       156      /* BMP  */
#define DATGUNBL02                       157      /* BMP  */
#define DATGUNBL03                       158      /* BMP  */
#define DATGUNBL04                       159      /* BMP  */
#define DATGUNBL05                       160      /* BMP  */
#define DATGUNBL06                       161      /* BMP  */
#define DATGUNBL07                       162      /* BMP  */
#define DATGUNBL08                       163      /* BMP  */
#define DATGUNBL09                       164      /* BMP  */
#define DATGUNBL10                       165      /* BMP  */
#define DATGUNBL11                       166      /* BMP  */
#define DATGUNBL12                       167      /* BMP  */
#define DATGUNF0001                      168      /* BMP  */
#define DATGUNF0002                      169      /* BMP  */
#define DATGUNF0003                      170      /* BMP  */
#define DATGUNF0004                      171      /* BMP  */
#define DATGUNF0005                      172      /* BMP  */
#define DATGUNF0006                      173      /* BMP  */
#define DATGUNF0007                      174      /* BMP  */
#define DATGUNF0008                      175      /* BMP  */
#define DATGUNF0009                      176      /* BMP  */
#define DATGUNF0010                      177      /* BMP  */
#define DATGUNF0011                      178      /* BMP  */
#define DATGUNF0012                      179      /* BMP  */
#define DATGUNF0013                      180      /* BMP  */
#define DATGUNF0014                      181      /* BMP  */
#define DATGUNL0001                      182      /* BMP  */
#define DATGUNL0002                      183      /* BMP  */
#define DATGUNL0003                      184      /* BMP  */
#define DATGUNL0004                      185      /* BMP  */
#define DATGUNL0005                      186      /* BMP  */
#define DATGUNL0006                      187      /* BMP  */
#define DATGUNL0007                      188      /* BMP  */
#define DATGUNL0008                      189      /* BMP  */
#define DATGUNL0009                      190      /* BMP  */
#define DATGUNL0010                      191      /* BMP  */
#define DATGUNL0011                      192      /* BMP  */
#define DATGUNL0012                      193      /* BMP  */
#define DATGUNL0013                      194      /* BMP  */
#define DATGUNL0014                      195      /* BMP  */
#define DATHANDLESS1                     196      /* BMP  */
#define DATHANDLESS2                     197      /* BMP  */
#define DATHANDLESS3                     198      /* BMP  */
#define DATHANDLESS4                     199      /* BMP  */
#define DATHEAD                          200      /* BMP  */
#define DATHEADLESS1                     201      /* BMP  */
#define DATHEADLESS2                     202      /* BMP  */
#define DATHEADLESS3                     203      /* BMP  */
#define DATHEADLESS4                     204      /* BMP  */
#define DATITEM001                       205      /* BMP  */
#define DATITEM002                       206      /* BMP  */
#define DATITEM003                       207      /* BMP  */
#define DATITEM004                       208      /* BMP  */
#define DATITEM005                       209      /* BMP  */
#define DATITEM006                       210      /* BMP  */
#define DATITEM007                       211      /* BMP  */
#define DATITEM008                       212      /* BMP  */
#define DATITEM009                       213      /* BMP  */
#define DATITEM010                       214      /* BMP  */
#define DATITEM011                       215      /* BMP  */
#define DATITEM012                       216      /* BMP  */
#define DATITEM013                       217      /* BMP  */
#define DATITEM014                       218      /* BMP  */
#define DATITEM015                       219      /* BMP  */
#define DATITEM016                       220      /* BMP  */
#define DATITEM017                       221      /* BMP  */
#define DATITEM018                       222      /* BMP  */
#define DATITEM019                       223      /* BMP  */
#define DATITEM020                       224      /* BMP  */
#define DATITEM021                       225      /* BMP  */
#define DATITEM022                       226      /* BMP  */
#define DATITEM023                       227      /* BMP  */
#define DATITEM024                       228      /* BMP  */
#define DATITEM025                       229      /* BMP  */
#define DATITEM026                       230      /* BMP  */
#define DATITEM027                       231      /* BMP  */
#define DATITEMBOX                       232      /* BMP  */
#define DATLASER01                       233      /* BMP  */
#define DATLASER02                       234      /* BMP  */
#define DATLASER03                       235      /* BMP  */
#define DATLASER04                       236      /* BMP  */
#define DATLEGLESS1                      237      /* BMP  */
#define DATLEGLESS2                      238      /* BMP  */
#define DATLEGLESS3                      239      /* BMP  */
#define DATLEGLESS4                      240      /* BMP  */
#define DATM1A1                          241      /* BMP  */
#define DATM1A2                          242      /* BMP  */
#define DATM1A3                          243      /* BMP  */
#define DATM1A4                          244      /* BMP  */
#define DATM1A5                          245      /* BMP  */
#define DATM1A6                          246      /* BMP  */
#define DATM1A7                          247      /* BMP  */
#define DATM1A8                          248      /* BMP  */
#define DATM1A9                          249      /* BMP  */
#define DATM1B1                          250      /* BMP  */
#define DATM1B2                          251      /* BMP  */
#define DATM1B3                          252      /* BMP  */
#define DATM1B4                          253      /* BMP  */
#define DATM1B5                          254      /* BMP  */
#define DATM1B6                          255      /* BMP  */
#define DATM1B7                          256      /* BMP  */
#define DATM1B8                          257      /* BMP  */
#define DATM1B9                          258      /* BMP  */
#define DATM2A1                          259      /* BMP  */
#define DATM2A2                          260      /* BMP  */
#define DATM2A3                          261      /* BMP  */
#define DATM2A4                          262      /* BMP  */
#define DATM2A5                          263      /* BMP  */
#define DATM2A6                          264      /* BMP  */
#define DATM2A7                          265      /* BMP  */
#define DATM2A8                          266      /* BMP  */
#define DATM2A9                          267      /* BMP  */
#define DATM2B1                          268      /* BMP  */
#define DATM2B2                          269      /* BMP  */
#define DATM2B3                          270      /* BMP  */
#define DATM2B4                          271      /* BMP  */
#define DATM2B5                          272      /* BMP  */
#define DATM2B6                          273      /* BMP  */
#define DATM2B7                          274      /* BMP  */
#define DATM2B8                          275      /* BMP  */
#define DATM2B9                          276      /* BMP  */
#define DATM3A1                          277      /* BMP  */
#define DATM3A2                          278      /* BMP  */
#define DATM3A3                          279      /* BMP  */
#define DATM3A4                          280      /* BMP  */
#define DATM3A5                          281      /* BMP  */
#define DATM3A6                          282      /* BMP  */
#define DATM3A7                          283      /* BMP  */
#define DATM3A8                          284      /* BMP  */
#define DATM3A9                          285      /* BMP  */
#define DATM3B1                          286      /* BMP  */
#define DATM3B2                          287      /* BMP  */
#define DATM3B3                          288      /* BMP  */
#define DATM3B4                          289      /* BMP  */
#define DATM3B5                          290      /* BMP  */
#define DATM3B6                          291      /* BMP  */
#define DATM3B7                          292      /* BMP  */
#define DATM3B8                          293      /* BMP  */
#define DATM3B9                          294      /* BMP  */
#define DATM4A1                          295      /* BMP  */
#define DATM4A2                          296      /* BMP  */
#define DATM4A3                          297      /* BMP  */
#define DATM4A4                          298      /* BMP  */
#define DATM4A5                          299      /* BMP  */
#define DATM4A6                          300      /* BMP  */
#define DATM4A7                          301      /* BMP  */
#define DATM4A8                          302      /* BMP  */
#define DATM4A9                          303      /* BMP  */
#define DATMAP0001                       304      /* BMP  */
#define DATMAP0002                       305      /* BMP  */
#define DATMAP0003                       306      /* BMP  */
#define DATMAP0004                       307      /* BMP  */
#define DATMAP0005                       308      /* BMP  */
#define DATMAP0006                       309      /* BMP  */
#define DATMAP0007                       310      /* BMP  */
#define DATMAP0008                       311      /* BMP  */
#define DATMAP0009                       312      /* BMP  */
#define DATMAP0010                       313      /* BMP  */
#define DATMAP0011                       314      /* BMP  */
#define DATMAP0012                       315      /* BMP  */
#define DATMAP0013                       316      /* BMP  */
#define DATMAP0014                       317      /* BMP  */
#define DATMAP0015                       318      /* BMP  */
#define DATMAP0016                       319      /* BMP  */
#define DATMAP0017                       320      /* BMP  */
#define DATMAP0018                       321      /* BMP  */
#define DATMAP0019                       322      /* BMP  */
#define DATMAP0020                       323      /* BMP  */
#define DATMAP0021                       324      /* BMP  */
#define DATMAP0022                       325      /* BMP  */
#define DATMAP0023                       326      /* BMP  */
#define DATMAP0024                       327      /* BMP  */
#define DATMAP0025                       328      /* BMP  */
#define DATMAP0026                       329      /* BMP  */
#define DATMAP0027                       330      /* BMP  */
#define DATMAP0028                       331      /* BMP  */
#define DATMAP0029                       332      /* BMP  */
#define DATMAP0030                       333      /* BMP  */
#define DATMAP0031                       334      /* BMP  */
#define DATMAP0032                       335      /* BMP  */
#define DATMAP0033                       336      /* BMP  */
#define DATMAP0034                       337      /* BMP  */
#define DATMAP0035                       338      /* BMP  */
#define DATMAP0036                       339      /* BMP  */
#define DATMAP0037                       340      /* BMP  */
#define DATMAP0038                       341      /* BMP  */
#define DATMAP0039                       342      /* BMP  */
#define DATMAP0040                       343      /* BMP  */
#define DATMAP0041                       344      /* BMP  */
#define DATMAP0042                       345      /* BMP  */
#define DATMAP0043                       346      /* BMP  */
#define DATMAP0044                       347      /* BMP  */
#define DATMAP0045                       348      /* BMP  */
#define DATMAP0046                       349      /* BMP  */
#define DATMAP0047                       350      /* BMP  */
#define DATMAP0048                       351      /* BMP  */
#define DATMAP0049                       352      /* BMP  */
#define DATMAP0050                       353      /* BMP  */
#define DATMAP0051                       354      /* BMP  */
#define DATMAP0052                       355      /* BMP  */
#define DATMAP0053                       356      /* BMP  */
#define DATMAP0054                       357      /* BMP  */
#define DATMAP0055                       358      /* BMP  */
#define DATMAP0056                       359      /* BMP  */
#define DATMAP0057                       360      /* BMP  */
#define DATMAP0058                       361      /* BMP  */
#define DATMAP0059                       362      /* BMP  */
#define DATMAP0060                       363      /* BMP  */
#define DATMAP0061                       364      /* BMP  */
#define DATMAP0062                       365      /* BMP  */
#define DATMAP0063                       366      /* BMP  */
#define DATMAP0064                       367      /* BMP  */
#define DATMAP0065                       368      /* BMP  */
#define DATMAP0066                       369      /* BMP  */
#define DATMAP0067                       370      /* BMP  */
#define DATMAP0068                       371      /* BMP  */
#define DATMAP0069                       372      /* BMP  */
#define DATMAP0070                       373      /* BMP  */
#define DATMAP0071                       374      /* BMP  */
#define DATMAP0072                       375      /* BMP  */
#define DATMAP0073                       376      /* BMP  */
#define DATMAP0074                       377      /* BMP  */
#define DATMAP0075                       378      /* BMP  */
#define DATMAP0076                       379      /* BMP  */
#define DATMAP0077                       380      /* BMP  */
#define DATMAP0078                       381      /* BMP  */
#define DATMAP0079                       382      /* BMP  */
#define DATMAP0080                       383      /* BMP  */
#define DATMAP0081                       384      /* BMP  */
#define DATMAP0082                       385      /* BMP  */
#define DATMAP0083                       386      /* BMP  */
#define DATMAP0084                       387      /* BMP  */
#define DATMAP0085                       388      /* BMP  */
#define DATMAP0086                       389      /* BMP  */
#define DATMAP0087                       390      /* BMP  */
#define DATMAP0088                       391      /* BMP  */
#define DATMAP0089                       392      /* BMP  */
#define DATMAP0090                       393      /* BMP  */
#define DATMAP0091                       394      /* BMP  */
#define DATMAP0092                       395      /* BMP  */
#define DATMAP0093                       396      /* BMP  */
#define DATMAP0094                       397      /* BMP  */
#define DATMAP0095                       398      /* BMP  */
#define DATMAP0096                       399      /* BMP  */
#define DATMAP0097                       400      /* BMP  */
#define DATMAP0098                       401      /* BMP  */
#define DATMAP0099                       402      /* BMP  */
#define DATMAP0100                       403      /* BMP  */
#define DATMAP0101                       404      /* BMP  */
#define DATMAP0102                       405      /* BMP  */
#define DATMAP0103                       406      /* BMP  */
#define DATMAP0104                       407      /* BMP  */
#define DATMAP9999                       408      /* BMP  */
#define DATMENUARMOR                     409      /* BMP  */
#define DATMENUBOX                       410      /* BMP  */
#define DATMENUBUY                       411      /* BMP  */
#define DATMENUBUY45                     412      /* BMP  */
#define DATMENUBUY762                    413      /* BMP  */
#define DATMENUBUY9MM                    414      /* BMP  */
#define DATMENUBUYAIM                    415      /* BMP  */
#define DATMENUBUYAMMO                   416      /* BMP  */
#define DATMENUBUYBAZOOKA                417      /* BMP  */
#define DATMENUBUYBAZOOKAAMMO            418      /* BMP  */
#define DATMENUBUYBOMB                   419      /* BMP  */
#define DATMENUBUYBUILD                  420      /* BMP  */
#define DATMENUBUYCAMOUFLAGE             421      /* BMP  */
#define DATMENUBUYCELLS                  422      /* BMP  */
#define DATMENUBUYDRILL                  423      /* BMP  */
#define DATMENUBUYENERGYW                424      /* BMP  */
#define DATMENUBUYGRAYPLATE              425      /* BMP  */
#define DATMENUBUYGRENADE                426      /* BMP  */
#define DATMENUBUYHEAVYPLASMA            427      /* BMP  */
#define DATMENUBUYHELMET                 428      /* BMP  */
#define DATMENUBUYHELMET2                429      /* BMP  */
#define DATMENUBUYHMISLAUNCHER           430      /* BMP  */
#define DATMENUBUYHOMER                  431      /* BMP  */
#define DATMENUBUYKEVLARPANTS            432      /* BMP  */
#define DATMENUBUYKEVLARPANTS2           433      /* BMP  */
#define DATMENUBUYLASERCANNON            434      /* BMP  */
#define DATMENUBUYLASERPISTOL            435      /* BMP  */
#define DATMENUBUYLASERRIFLE             436      /* BMP  */
#define DATMENUBUYLASERSABRE             437      /* BMP  */
#define DATMENUBUYLAVABOMB               438      /* BMP  */
#define DATMENUBUYLAVATRAP               439      /* BMP  */
#define DATMENUBUYMACHINEGUN             440      /* BMP  */
#define DATMENUBUYMAGNUM                 441      /* BMP  */
#define DATMENUBUYMEDIKIT                442      /* BMP  */
#define DATMENUBUYPARACHUTE              443      /* BMP  */
#define DATMENUBUYPISTOL                 444      /* BMP  */
#define DATMENUBUYPLASMAPISTOL           445      /* BMP  */
#define DATMENUBUYPLASMAPODS             446      /* BMP  */
#define DATMENUBUYPROJECTW               447      /* BMP  */
#define DATMENUBUYSELFDESTRUCTOR         448      /* BMP  */
#define DATMENUBUYSHELLS                 449      /* BMP  */
#define DATMENUBUYSHOTGUN                450      /* BMP  */
#define DATMENUBUYSNIPER                 451      /* BMP  */
#define DATMENUBUYSUBMACHINEGUN          452      /* BMP  */
#define DATMENUBUYSUPERLAVATRAP          453      /* BMP  */
#define DATMENUBUYTOOLS                  454      /* BMP  */
#define DATMENUBUYTOOLSTOOLS             455      /* BMP  */
#define DATMENUBUYVEHICLE1               456      /* BMP  */
#define DATMENUBUYVEHICLE2               457      /* BMP  */
#define DATMENUBUYVEST                   458      /* BMP  */
#define DATMENUBUYVEST2                  459      /* BMP  */
#define DATMENUBUYWEAPONS                460      /* BMP  */
#define DATMENUBUYWHITEPLATE             461      /* BMP  */
#define DATMENUCROSS                     462      /* BMP  */
#define DATMENUINVENTORY                 463      /* BMP  */
#define DATMONEY                         464      /* BMP  */
#define DATNINJAROPE                     465      /* BMP  */
#define DATPALETTE                       466      /* PAL  */
#define DATPARACHUTE                     467      /* BMP  */
#define DATPBDEATH01                     468      /* BMP  */
#define DATPBDEATH02                     469      /* BMP  */
#define DATPBDEATH03                     470      /* BMP  */
#define DATPBDEATH04                     471      /* BMP  */
#define DATPBDEATH05                     472      /* BMP  */
#define DATPBDEATH06                     473      /* BMP  */
#define DATPBDEATH07                     474      /* BMP  */
#define DATPBDEATH08                     475      /* BMP  */
#define DATPBDEATH09                     476      /* BMP  */
#define DATPBDEATH10                     477      /* BMP  */
#define DATPBDEATH11                     478      /* BMP  */
#define DATPBDEATH12                     479      /* BMP  */
#define DATPLASMADEATH01                 480      /* BMP  */
#define DATPLASMADEATH02                 481      /* BMP  */
#define DATPLASMADEATH03                 482      /* BMP  */
#define DATPLASMADEATH04                 483      /* BMP  */
#define DATPLASMADEATH05                 484      /* BMP  */
#define DATPLASMADEATH06                 485      /* BMP  */
#define DATPLASMADEATH07                 486      /* BMP  */
#define DATPLASMADEATH08                 487      /* BMP  */
#define DATPLASMADEATH09                 488      /* BMP  */
#define DATPLASMADEATH10                 489      /* BMP  */
#define DATPLASMADEATH11                 490      /* BMP  */
#define DATPLASMADEATH12                 491      /* BMP  */
#define DATSEVEREHEAD                    492      /* BMP  */
#define DATSEVEREHEAD2                   493      /* BMP  */
#define DATSHRAPNEL01                    494      /* BMP  */
#define DATSHRAPNEL02                    495      /* BMP  */
#define DATSHRAPNEL03                    496      /* BMP  */
#define DATVEHICLE1_01                   497      /* BMP  */
#define DATVEHICLE1_02                   498      /* BMP  */
#define DATVEHICLE1_03                   499      /* BMP  */
#define DATVEHICLE1_04                   500      /* BMP  */
#define DATVEHICLE1_05                   501      /* BMP  */
#define DATVEHICLE1_06                   502      /* BMP  */
#define DATVEHICLE1_07                   503      /* BMP  */
#define DATVEHICLE1_08                   504      /* BMP  */
#define DATVEHICLE1_09                   505      /* BMP  */
#define DATVEHICLE1_10                   506      /* BMP  */
#define DATVEHICLE1_11                   507      /* BMP  */
#define DATVEHICLE1_12                   508      /* BMP  */
#define DATVEHICLE1_13                   509      /* BMP  */
#define DATVEHICLE2_01                   510      /* BMP  */
#define DATVEHICLE2_02                   511      /* BMP  */
#define DATVEHICLE2_03                   512      /* BMP  */
#define DATVEHICLE2_04                   513      /* BMP  */
#define DATWEAPONHAND1                   514      /* BMP  */
#define DATWHITEPLATE                    515      /* BMP  */
#define DATWITHHEAD1                     516      /* BMP  */
#define DATWITHHEAD2                     517      /* BMP  */
#define DATWITHHEAD3                     518      /* BMP  */
#define DATWITHHEAD4                     519      /* BMP  */
#define DATWITHHEAD5                     520      /* BMP  */
#define FONT1                            521      /* FONT */
#define FONT2                            522      /* FONT */
#define SMALLFONT                        523      /* FONT */
#define TITLE                            524      /* RLE  */
#define TITLEARROW                       525      /* BMP  */
#define TITLECOPYRIGHT                   526      /* BMP  */
#define TITLECURSOR                      527      /* BMP  */
#define TITLEFONT                        528      /* FONT */
#define TITLEPAL                         529      /* PAL  */

